AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - script/**
    - Gemfile
    - Rakefile

AllCops:
  TargetRubyVersion: 2.6

StringLiterals:
  EnforcedStyle: single_quotes

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded
  SupportedStyles:
    - compact
    - expanded

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - system/boot/*

Metrics/LineLength:
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

Style/LambdaCall:
  Enabled: false
